#
# ~/.bashrc
#

# This is a clean bashrc file, generated by KDP in userscripts
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export PATH=$PATH:~/userscripts/execscripts
export PATH=$PATH:~/userscripts/execscripts/sync
<<<<<<< HEAD
export PATH=$PATH:~/userscripts/execscripts/vimswitch
export PATH=$PATH:~/userscripts/installation/optional
export TERM=xterm-256color

# GOLANG
export GOPATH=~/Documents/projects/golang
export PATH="$PATH:$GOPATH/bin"
=======
export PATH=$PATH:~/userscripts/execscripts/local
>>>>>>> 00285efd37ff4a911f3478feba8c96f29197ee74
