#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## Synchronize userscripts with github
##########################################################################

echo "--------------------------------------------------------------------------------------"
echo "-- Profile SyncScript - Made by KDP                                                  --"
echo "--------------------------------------------------------------------------------------"

# start copying files
echo "Starting copying files."
cp ~/userscripts/dotfiles/.bashrc ~/.bashrc
