#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## Synchronize userscripts with github
##########################################################################

# start copying files
echo "Starting copying files."
cp ~/userscripts/dotfiles/.bashrc ~/.bashrc
