#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## Synchronize userscripts with github
##########################################################################

# print banner
#echo "--------------------------------------------------------------------------------------"
#echo "-- Github SyncScript" 
#echo "--------------------------------------------------------------------------------------"
#echo " " 

# specific banner
cd $1 
echo "******"
echo "Syncing repo $1"
echo "******"
echo " "

# Add all altered files to the git commit
echo "Adding new/moderated files (if any) to the commit."
git add -A 2>&1 | sed 's/^/    /' 
echo " "
echo "  Added files:"
git diff --cached --name-only 2>&1 | sed 's/^/    /'
echo " "

# Commit the changes to git with a current timestamp to the commit message
echo "Starting git commit... ."
git commit -m "Syncscript executed on `date +'%Y-%m-%d %H:%M:%S'` from $HOSTNAME." 2>&1 | sed 's/^/    /'
echo " "

# Push to git
echo "Starting push to github... ."
git push 2>&1 | sed 's/^/    /' 
echo " "

# Pulling from git 
echo "Starting pull from github... ."
git pull 2>&1 | sed 's/^/    /'
echo " " 

# Ending banner
echo "~~ sync done. ~~"
#echo "--------------------------------------------------------------------------------------"
