#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## Synchronize userscripts with github
##########################################################################

# clear the screen
printf "\033c"
echo "======================================================================================"
echo "== KSyncScript - Made by KDP                                                        =="
echo "======================================================================================"
echo " " 
source ksyncGit ~/userscripts
source ksyncGit ~/Documents/projects/golang/src/github.com/kimdepypere/golangProjects
echo " " 
#Disabled bashrc synchro for safety purposes.
# source ksyncProfile
echo " " 
echo "======================================================================================"
