#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## Synchronize userscripts with github
##########################################################################

# clear the screen
printf "\033c"
echo "--------------------------------------------------------------------------------------"
echo "-- KSyncScript - Made by KDP                                                        --"
echo "--------------------------------------------------------------------------------------"
echo " " 
echo "Starting syncGit"
echo " "
source ksyncGit
echo "Starting ksyncProfile"
source ksyncProfile
echo " " 
echo "--------------------------------------------------------------------------------------"
