#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    22/12/2016
## Description:
## Install a GoLang specific vimrc  
##########################################################################

# gocode
echo "Installing gocode"
go get -u github.com/nsf/gocode

# godef
echo "Installing godef"
go get -u github.com/rogpeppe/godef

# gotags
echo "Installing gotags"
go get -u github.com/jstemmer/gotags

# # goimports
# echo "Installing goimports"
# go get -u golang.org/x/tools/cmd/goimports
#
# # golint
# echo "Installing golint"
# go get -u github.com/golang/lint/golint
#
# # errcheck
# echo "Installing errcheck"
# go get -u github.com/kisielk/errcheck
#
# # oracle
# echo "Installing oracle"
# go get -u golang.org/x/tools/cmd/oracle
