#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## Install personal directory-structure
##########################################################################

cd ~/
echo "Making documents folder"
mkdir ~/Documents
echo "Making projects folder"
mkdir ~/Documents/projects
echo "Making go folder"
mkdir ~/Documents/projects/golang
cd ~/Documents/projects/golang
mkdir {src,pkg,bin}
cd src
mkdir github.com
cd github.com
mkdir kimdepypere
cd kimdepypere
git clone https://github.com/kimdepypere/golangProjects
cd golangProjects
git remote set-url origin git@github.com:kimdepypere/golangProjects.git
cd ~/
echo "Making ruby folder"
mkdir ~/Documents/projects/ruby
echo "Making php folder"
mkdir ~/Documents/projects/php
echo "Making python folder"
mkdir ~/Documents/projects/python

echo "Making published folder"
mkdir ~/Documents/projects/published

