#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    22/12/2016
## Description:
## Install a GoLang specific vimrc  
##########################################################################

cd ~/.vim/bundle

#install plugins
git clone https://github.com/scrooloose/nerdtree.git 
git clone --depth=1 https://github.com/vim-syntastic/syntastic.git  
git clone https://github.com/vim-airline/vim-airline 
git clone https://github.com/scrooloose/nerdcommenter.git
