#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    22/12/2016
## Description:
## Install a GoLang specific vimrc  
##########################################################################

mkdir ~/.vim/bundle
cd ~/.vim/bundle
echo "-------------------------------------------------------"
#install plugins
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree 
#git clone --depth=1 https://github.com/vim-syntastic/syntastic.git & 
git clone https://github.com/vim-syntastic/syntastic.git ~/.vim/bundle/syntastic  
git clone https://github.com/vim-airline/vim-airline ~/.vim/bundle/vim-airline 
git clone https://github.com/scrooloose/nerdcommenter.git ~/.vim/bundle/nerdcommenter 
echo "-------------------------------------------------------"
