#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    22/12/2016
## Description:
## Install a GoLang specific vimrc  
##########################################################################

cd ~/
mkdir .vim

#remove old bundles 
rm -r -f .vim/bundle 
mkdir .vim/bundle

#install custom colors (molokai theme)
cd ~/.vim 
mkdir colors
cd ~/.vim/bundle

# Favourite themes github download
git clone https://github.com/NLKNguyen/papercolor-theme ~/.vim/bundle/papercolor-theme
git clone https://github.com/ciaranm/inkpot ~/.vim/bundle/inkpot

mv ~/.vim/bundle/papercolor-theme/colors/PaperColor.vim ~/.vim/colors
mv ~/.vim/bundle/inkpot/colors/inkpot.vim ~/.vim/colors

# Cleanup
rm -r -f ~/.vim/bundle/papercolor-theme
rm -r -f ~/.vim/bundle/inkpot
