#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## installation script for new users 
##########################################################################

# === add SSH keys information ==
# echo "Making ssh key's"
# ssh-keygen -t rsa -b 4096 -C "email@gmail.com"

#if [ -f "~/.ssh/id_rsa.pub" ]; then
#    echo "id_rsa.pub found."
#else 
#    echo "id_rsa.pub not found."
#fi

echo "Syncing userscripts... ."
cd ~/
git clone https://github.com/kimdepypere/userscripts
cd  ~/userscripts
git remote set-url origin git@github.com:kimdepypere/userscripts.git
cd ~/

#Adding a local executescript which will not be synced with github.
cd ~/userscripts/execscripts
mkdir local
cd ~/userscripts
echo "execscripts/local" > .gitignore
cd ~/


echo "Patching config-file for x11-forwarding problems with github."
echo "Host *github.com*" >> ~/.ssh/config 
echo "   ForwardX11 no" >> ~/.ssh/config

echo "Linking files... ."
rm ~/.vimrc
ln -s ~/userscripts/dotfiles/.vimrc ~/.vimrc

echo "Copying bashrc to local user."
cp ~/userscripts/dotfiles/.bashrc ~/.bashrc

echo "Making scripts executable... ."
chmod 700 -R ~/userscripts/execscripts

echo "Add the following key to github-keys:"
echo "-----------------------------------"
cat ~/.ssh/id_rsa.pub
echo "-----------------------------------"
echo " "
echo "End of script."
