#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    22/12/2016
## Description:
## installation script for new users 
##########################################################################

# === add SSH keys information ==
# echo "Making ssh key's"
# ssh-keygen -t rsa -b 4096 -C "email@gmail.com"

#if [ -f "~/.ssh/id_rsa.pub" ]; then
#    echo "id_rsa.pub found."
#else 
#    echo "id_rsa.pub not found."
#fi

echo "Syncing userscripts... ."
cd ~/
git clone https://github.com/kimdepypere/userscripts
cd  ~/userscripts
git remote set-url origin git@github.com:kimdepypere/userscripts.git
cd ~/

#Adding a local executescript which will not be synced with github.
cd ~/userscripts/execscripts
mkdir local
cd ~/userscripts
echo "execscripts/local" > .gitignore
cd ~/


echo "Patching config-file for x11-forwarding problems with github."
echo "Host *github.com*" >> ~/.ssh/config 
echo "   ForwardX11 no" >> ~/.ssh/config

echo "Removing existing files."
rm ~/.vimrc
echo "Copying files... ."
echo " - Using empty vimrc."
cp ~/userscripts/dotfiles/vimrcEmpty ~/.vimrc

echo "Installing vim specifics."
echo " - Installing vim plugin manager pathogen."
source ~/userscripts/installation/optional/installVimPluginManager
wait
echo " - Installing vim plugins"
source ~/userscripts/installation/optional/installVimPathogenPlugins
wait
echo " - Installing vim themes"
source ~/userscripts/installation/optional/installVimThemes

echo "Copying .bashrc to local user."
cp ~/userscripts/dotfiles/.bashrc ~/.bashrc

echo "Making scripts executable... ."
chmod 700 -R ~/userscripts/execscripts

echo "Add the following key to github-keys:"
echo "-----------------------------------"
cat ~/.ssh/id_rsa.pub
echo "-----------------------------------"
echo " "
echo "End of script."
