#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    22/12/2016
## Description:
## installation script for new users 
##########################################################################

#======= INFO(start)

#echo "Making ssh key's"
#ssh-keygen -t rsa -b 4096 -C "email@gmail.com"

#if [ -f "~/.ssh/id_rsa.pub" ]; then
#    echo "id_rsa.pub found."
#else 
#    echo "id_rsa.pub not found."
#fi

#======= INFO(end) 

#======= Sync
echo "Syncing userscripts... ."
cd ~/
git clone https://github.com/kimdepypere/userscripts
cd  ~/userscripts
git remote set-url origin git@github.com:kimdepypere/userscripts.git
cd ~/

#======= Make a local executescript directory (non-sync with gibhug)
echo 'Making a local executable directory (~/userscripts/execscripts/local)'
cd ~/userscripts/execscripts
mkdir local
cd ~/userscripts
echo "Exlcuding local executable directory from github sync."
echo "execscripts/local" > .gitignore
cd ~/

#======= Patch config-file
echo "Patching config-file for x11-forwarding problems with github."
echo "Host *github.com*" >> ~/.ssh/config 
echo "   ForwardX11 no" >> ~/.ssh/config

#======= Remove existing files
echo "Removing existing files."
rm ~/.vimrc

#======= Remove existing directories
echo "Removing .vim directory."
rm -rf ~/.vim

#======= Adding new directories
echo "Adding new .vim directory."
mkdir ~/.vim

#======= Adding bashrc files
echo "Adding bashrc-files." 
cp ~/userscripts/dotfiles/bash/.bashrc ~/.bashrc

#======= Adding vimrc files
echo "Adding vimrc-files."
cp ~/userscripts/dotfiles/vim/.vimrc ~/.vimrc
cp -R ~/userscripts/dotfiles/vim/.vim ~/.vim

#======= Installing vim dependencies
echo "Installing vim dependencies."

echo " - Installing vim plugin manager pathogen."
source ~/userscripts/installation/installscripts/installVimPluginManager
wait

echo " - Installing vim plugins"
source ~/userscripts/installation/installscripts/installVimPathogenPlugins
wait

echo " - Installing vim themes"
source ~/userscripts/installation/installscripts/installVimThemes
wait

#======= Installing executable scripts 
echo "Making scripts executable... ."
chmod 700 -R ~/userscripts/execscripts

#======= Display extra information
echo "Add the following key to github-keys:"
echo "-----------------------------------"
cat ~/.ssh/id_rsa.pub
echo "-----------------------------------"
echo " "
echo "End of script."
