#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## disable a service in systemd 
##########################################################################

sudo systemctl stop $1
sudo systemctl disable $1
