#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## Synchronize userscripts with github
##########################################################################

printf "\033c"
echo "-------------------------------------------"
echo "-- github syncscript - Made by KDP        -"
echo "-------------------------------------------"
echo "Starting sync... ."
cd ~/userscripts
echo "Adding all adaptations to gitsync... ."
git add -A | sed 's/^/    /'
echo "Starting git commit."
git commit -m "Syncscript executed on `date +'%Y-%m-%d %H:%M:%S'`." | i sed 's/^/    /'
echo "Pusching to github."
git push | sed 's/^/    /' 
echo "-------------------------------------------"
