#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## Synchronize userscripts with github
##########################################################################

printf "\033c"
echo "-------------------------------------------"
echo "-- github syncscript - Made by KDP        -"
echo "-------------------------------------------"
echo "Starting sync... ."
cd ~/userscripts
echo "Starting to add adaptations to gitsync... ."
git add -A 2>&1 | sed 's/^/    /' 
echo "Starting git commit."
git commit -m "Syncscript executed on `date +'%Y-%m-%d %H:%M:%S'`." 2>&1 | sed 's/^/    /'
echo "Pushing to github."
git push 2>&1 | sed 's/^/    /' 
echo "Stopping script."
echo "-------------------------------------------"
