#!/bin/bash

##########################################################################
## Author:  Kim Depypere
## Date:    04/12/2016
## Description:
## show all services in systemd
##########################################################################

systemctl | grep service
